name: hamfakedet_cicd

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  deploy_to_dockerhub:
    runs-on: ubuntu-latest
    environment: 
        name: prod
        
    steps:
      - uses: actions/checkout@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args:
            telegram_token=${{ secrets.TELEGRAM_TOKEN }}
          push: true
          tags: ${{ secrets.DOCKER_REPOSITORY }}/hamfakedet:latest

  deploy_to_kubernetes:
    runs-on: ["self-hosted", "Linux"]
    needs: deploy_to_dockerhub
    environment:
        name: prod
    
    steps:
      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: --insecure-skip-tls-verify apply -f deploy/deployment.yml
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.20"
        with:
          args: '"rollout status deployment/hamfakedet"'