name: hamfakedet_cicd

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_to_dockerhub:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Logins to dockerhub
      name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Builds the docker image
      - name: docker build
        run: docker build -t hamfakedet --no-cache --build-arg telegram_token=${{ secrets.TELEGRAM_TOKEN}} .

      # Pushes the image a docker repository
      - name: docker push
        run: docker tag hamfakedet:latest ${{ secrets.DOCKER_REPOSITORY }}/hamfakedet:latest
